pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker {
                    image 'maven:3.8.1-adoptopenjdk-11'
                    args '-v $HOME/.m2:/root/.m2' // Mounting local Maven repository for caching dependencies
                }
            }
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Front-end') {
            agent {
                docker {
                    image 'node:16-alpine'
                    args '-v $HOME/.npm:/root/.npm' // Mounting local NPM cache for dependency caching
                }
            }
            steps {
                sh 'npm install'
            }
        }
    }
}
